baseURL = '/'
title = 'My Kutub'
theme = 'writebook'
disableKinds = ["taxonomy", "term"]
relativeURLs = false
canonifyURLs = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    label = 'English'
    weight = 1
    title = 'Bookshelf'
    [languages.en.params]
      description = "A collection of my books."
